### ISSUE TITLE
Output Tweaking

### ISSUE THREAD

**Issue by devgc** [omerbenamram/evtx#12]
Just a small feature request. Could you exclude the null chars in output? It breaks a lot of processing of the output.

![image](https://user-images.githubusercontent.com/8633196/56373862-28a41300-61bf-11e9-8aac-fd38845dbc4f.png)

Also, there seems to be a formatting issue with integer rendering when the hex value is 1 char. A space between 0x and the integer. I know they are small things, but, it helps a lot when trying to serialize for ingestion or post processing.

**Comment by omerbenamram** [comment]
Will fix this today :)

**Comment by omerbenamram** [comment]
should be fixed in #13.
Thanks for letting me know of these small things :)

**Comment by devgc** [comment]
Another formatting request.

For binary blobs, can you make the output a hex string [Exmple: '000000000400000028C6AB67E9AA6AB4...']?

The list of ints is harder to post process. Example of current output (PartitionTable, MBR, etc.):
![image](https://user-images.githubusercontent.com/8633196/56379534-29dc3c80-61cd-11e9-8e15-5490cb5f34c7.png)

**Comment by omerbenamram** [comment]
added to #13. :)

**Comment by omerbenamram** [comment]
@devgc added to 0.1.8 patch :shipit:
