### ISSUE TITLE
Issue installing the evtx library on windows

### ISSUE THREAD

**Issue by ahmedkhlief** [omerbenamram/evtx#171]
Hi , Thanks for the library . i have one question regarding installing the library on windows as it shows below error . am using latest python3.9 .

Collecting evtx
  Using cached evtx-0.6.8.tar.gz (2.2 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-yxibz94l\\evtx_04d644cd67554da6b2028e9d4b820743\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-yxibz94l\\evtx_04d644cd67554da6b2028e9d4b820743\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-cylfeyzm'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-yxibz94l\evtx_04d644cd67554da6b2028e9d4b820743\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-yxibz94l\evtx_04d644cd67554da6b2028e9d4b820743\setup.py", line 34, in <module>
        RustExtension(
    TypeError: __init__() got an unexpected keyword argument 'target'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/33/18/b32715bae61c4fe6a7cdb79aafccb0d4797a1bfef028e9689197af214966/evtx-0.6.8.tar.gz#sha256=414507b79fe997a35fbf05ae57dd2f55a7acfc669b19d9125a894ffe40dbeade (from https://pypi.org/simple/evtx/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by omerbenamram** [comment]
Hi, I'm not yet publishing wheels for python 3.9

You'll need to build pyevtx from source to use with 3.9.
Wheels are automatically building for 3.6-3.8

**Comment by ahmedkhlief** [comment]
Thanks for your response and your efforts for building and maintaing this library .

**Comment by janstarke** [comment]
This issue applies to version *0.6.8*, but `evtx` is at *0.7.2* now. Has it been fixed in the meantime?

**Comment by omerbenamram** [comment]
@janstarke yes
