### ISSUE TITLE
Output date range of evtx

### ISSUE THREAD

**Issue by defensivedepth** [omerbenamram/evtx#187]
Looking for a way to quickly output the date range of a particular evtx ie:

Oldest log: 2/2/20
Newest log: 3/15/20

Something like what this cmdlet does:

`Get-WinEvent -Path 'C:\workspace\Security.evtx' -MaxEvents 1 -oldest | Select-Object -Property TimeCreated`

Any ideas?

**Comment by omerbenamram** [comment]
This can be done easily with jq/python.

`cargo run -- -o jsonl samples/Application.evtx --separate-json-attributes | jq '.Event.System.TimeCreated_attributes.SystemTime' | sort | head -n 1`

**Comment by defensivedepth** [comment]
Thanks!
