### ISSUE TITLE
# in JSON field name prevents import in GCP Bigquery

### ISSUE THREAD

**Issue by olamotte** [omerbenamram/evtx#198]
Thanks for the effort to build this great tool, we're throwing it a forwarded log files and really appreciate the performance boost! 

There's one minor step which required preprocessing for our use case, as we are loading data in Google's Bigquery. 

I unfortunately don't have a build environment setup for rust atm, but it seems the responsible code is here, impacting both #attributes and #text:

![image](https://user-images.githubusercontent.com/478103/127356534-786f3cea-238a-4f82-874c-a209301084a7.png)

https://github.com/omerbenamram/evtx/blob/0950198ed6c0f2381b1fc0b79c1fa4d094f638f3/src/json_output.rs#L239
https://github.com/omerbenamram/evtx/blob/0950198ed6c0f2381b1fc0b79c1fa4d094f638f3/src/json_output.rs#L321

Is there a reason i'm missing to use a special character in these two field names? It's a rather minor issue and we can run sed, but it would save some steps. 

Thanks in advance!

**Comment by forensicmatt** [comment]
Hey @olamotte I highly recommend using the `--separate-json-attributes`. all element attributes are stored under the `<FIELD_NAME>_attributes` field name thus there are no `#attributes` and `#text` field names.

**Comment by olamotte** [comment]
I had missed this - Thanks a lot!
