### ISSUE TITLE
README tweak

### ISSUE THREAD

**Issue by EricZimmerman** [omerbenamram/evtx#74]
this statement "For single core performance, it is both the fastest and the only parser than supports both xml and JSON outputs."

is not accurate as my project supports XML and json output

![image](https://user-images.githubusercontent.com/4265254/72167765-c668ef00-3399-11ea-922a-a1fb13227846.png)

**Comment by omerbenamram** [comment]
I forgot to mention I only benchmarked cross-platform parsers (windows users can always use winapi specific tooling).

Last time I checked I couldn't get EvtxECmd to run on linux (dotnet core), is this still the case?

**Comment by EricZimmerman** [comment]
yes, as of now i have not ported to .net core as i was/am waiting for it to stabilize. 

winapi based tools (can) miss a ton of stuff

**Comment by EricZimmerman** [comment]
also, no one will beat rust for speed! you will always wear that crown. this is a great project

**Comment by omerbenamram** [comment]
I’ll update the Readme to reflect the fact that I only benchmark other projects offering cross platform support. 

If you do add support for non-windows targets drop me a note and I’ll try to build it and benchmark it as well!

**Comment by EricZimmerman** [comment]
sounds good. closing
