### ISSUE TITLE
could not reproduce described behavior

### ISSUE THREAD

**Issue by khabibd** [omerbenamram/evtx#83]
> `fd -e evtx -x evtx_dump -f "{.}.xml` will create an xml file next to each evtx file, for all files in folder recursively!

Got:

```
error: The following required arguments were not provided:
    <INPUT>

USAGE:
    evtx_dump <INPUT> --ansi-codec <ansi-codec> --threads <num-threads> --format <output-format>

For more information try --help
```
Thx for this stuff, really handy tool :)

**Comment by omerbenamram** [comment]
It seems to a difference in behavior of fd when using windows..
try `fd -e evtx -x evtx_dump '{}' -f 'C:\Temp\{.}.xml'`
