### ISSUE TITLE
Feature Request: RunAsService or residential option

### ISSUE THREAD

**Issue by mveplus** [omerbenamram/evtx#84]
Would you consider implementing a constant log monitoring option "-d --run-as-service"?  

The idea is to monitor a single evtx log for changes and feed them to STDOUT a or a xml/json file so the new changes can be streamed to another host for processing. 

The way it works now when it finishes processing the evtx log file evtx_dump exits. 

Awesome work by the way! Thank you!

**Comment by omerbenamram** [comment]
Sorry, this isn't something I'm willing to commit time to.
This isn't a trivial feature to implement cross-platform support for, and I have no use for such feature.
