### ISSUE TITLE
Multi-threading not enabled by default when using the library

### ISSUE THREAD

**Issue by Ektoplasma** [omerbenamram/evtx#86]
Hello,

I try to use the library mode of evtx, because I need to script additional things (I want to send it to a Splunk instance). Maybe I missed something but the multithreading does not seem to be enabled. See the two following pictures showing a test with a 20Mo Application evtx file, with the binary, and with the library:

Binary mode:  
![evtx_binary](https://user-images.githubusercontent.com/15208659/80602992-20b4bb00-8a30-11ea-86a6-cf8ba93082d2.png)

Library mode:  
![evtx_library](https://user-images.githubusercontent.com/15208659/80604584-2f9c6d00-8a32-11ea-8324-f43c98b6d899.png)

Any idea ? Maybe I should add additional things on the Cargo configuration file. 

Observe that for the library mode, the additional threads are created but not used.
Best regards,
ekt0

**Comment by omerbenamram** [comment]
Hi, multi-threading is enabled by default when using the library.
It's controlled by the `multithreading` feature flag, which is enabled by default.

You can compare your code against the sources of `evtx-dump` and see where they diverge.
I cannot provide any further help without looking at the code at question.

**Comment by Ektoplasma** [comment]
Got it, after reading your code I figured that I needed to precise the number of threads, which is 0 for "please use as many threads as possible":

before:
```Rust
    let mut parser = EvtxParser::from_path(fp)
        .unwrap();
```

after:
```Rust
    let mut parser = EvtxParser::from_path(fp)
        .unwrap()
        .with_configuration(ParserSettings::new().num_threads(0));
```

Thanks !
